---
name: Pull Request Test
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  test-openstack-roles:
    name: Test Collection Openstack Roles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version: ["master"]
        # python: [ pypy3.8 ]
        python: [ 3.11 ]
        roles: [openstack_vm]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.11
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: 's-account,s-container,s-object,s-proxy'
# 'ir-api,ir-cond,s-account,s-container,s-object,s-proxy,q-svc,q-agt,q-dhcp,q-l3,q-meta,-cinder,-c-sch,-c-api,-c-vol,-c-bak,-ovn,-ovn-controller,-ovn-northd,-q-ovn-metadata-agent'
          cache: devstack
      - name: Install Python
        uses: actions/setup-python@v4 
        with:
          python-version:  ${{ matrix.python }}
          cache: pip
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Build Ansible Collection
        run: ansible-galaxy collection build ansible/ansible_collections/snowdrop/cloud_infra --output build/ --force
      - name: Install Ansible Collection
        run: ansible-galaxy collection install ./build/snowdrop-cloud_infra-1.0.0.tar.gz --upgrade
      - name: Run tests
        run: |
          # python3 -m venv .snowdrop-venv
          # source .snowdrop-venv/bin/activate
          # pip install -r requirements.txt
          # python3 -m pip install -r requirements.txt
          molecule test --scenario-name github
        working-directory: ansible/ansible_collections/snowdrop/cloud_infra/roles/${{ matrix.roles }}
...
# + home/runner/work/k8s-infra/k8s-infra/devstack/tools/create_userrc.sh:main:241 :   read project_id project_name desc enabled
# Failed to discover available identity versions when contacting http://localhost:5000/v3/. Attempting to parse version from URL.
# Unable to establish connection to http://localhost:5000/v3/auth/tokens: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfe0ee6d70>: Failed to establish a new connection: [Errno 111] Connection refused'))
